### ISSUE TITLE
Look for videos that failed to download

### ISSUE THREAD

**Issue by matcha6666** [EchterAlsFake/Porn_Fetch#10]
Hi，
How do I view the video where my download failed?

**Comment by matcha6666** [comment]
Because I found that the downloaded video is not complete, compared and found that the video of the same duration, some will fail to download, and there is a problem that the title of the video will be changed, which is different from the original title on the website.

**Comment by EchterAlsFake** [comment]
Hi, the title is changed, because the API language is by default set to EN (English) and therefore all titles are in English (if available).  I don't understand what you mean with your first question.

The video download failed and when you view the video the duration isn't the same than on the website?

If that's the problem, the solution is simple.

If the download fails for some reason then you only have the parts of the video of the downloaded content. You just need to delete the previous download and re-download the video.  If the download successfully completes, there shouldn't be a problem.


But to come back to the title, 

I can if you want make an update to set a custom API language. It would be zh-CN for the "easier" chinese how it's used in general china, zh-TW for the traditional chinese in Taiwan, zh-HK for the traditional chinese in Hongkong and zh-SG for chinese being used in Singapure.

If you don't want to specify the region, you can just use "zh"

I'll implement that as soon as possible. I tell you when it's finished.

**Comment by matcha6666** [comment]
I understand that your title will change, it should be that the language I set on the website is different, and the app uses English, so the title is different.

**Comment by matcha6666** [comment]
The problem with video download failure is that in the same model's video, for example, if there are two videos of the same 1 minute, sometimes he will only download one of them, and the other 1-minute video will not be downloaded.

**Comment by matcha6666** [comment]
> 我知道你的标题会改变，应该是我在网站上设置的语言不同，而且应用程序使用英语，所以标题不同。

Custom language settings are not much needed for me, and I know what the problem is when I see your answer.

**Comment by EchterAlsFake** [comment]
Can you please tell me what model it is, so that I can reproduce that error?

**Comment by matcha6666** [comment]
> 你能告诉我它是什么模型，以便我可以重现该错误吗
I can't provide it because it's random, one moment there is, the other moment there is not, it feels like luck.

**Comment by EchterAlsFake** [comment]
Ah okay.  So I am doing some tests now and try to fix it :)

**Comment by EchterAlsFake** [comment]
So I updated the releases with the fixed commit. You can now set a custom API language in the input field in the settings and then apply it with the button.  Try setting it zo "zh" and see if the error still persists. If that doesn't fix it, I don't know what else to do.

**Comment by matcha6666** [comment]
> So I updated the releases with the fixed commit. You can now set a custom API language in the input field in the settings and then apply it with the button. Try setting it zo "zh" and see if the error still persists. If that doesn't fix it, I don't know what else to do.

OK, I'll use it, thank you for the features you added to the program.
