### ISSUE TITLE
Playlist Support?

### ISSUE THREAD

**Issue by RonLar1132** [EchterAlsFake/Porn_Fetch#20]

**Comment by EchterAlsFake** [comment]
Hi,

I can already think of what you want, but just to be sure...

Do you want me to add support for PornHub playlists, so that if you enter the URL of the playlist, all videos of that playlists can be downloaded? If Yes, that would be possible, but I'd need to implement this in the PHUB API which would maybe take some days.

If not, please correct me, thanks :)

**Comment by RonLar1132** [comment]
Yeah. Support for private playlists, and public?

**Comment by EchterAlsFake** [comment]
Okay, so I looked up on it and should be possible. Private playlists should also be possible, if you are logged in. I a working on it.

**Comment by EchterAlsFake** [comment]
Okay so I've implemented playlist support into PHUB and Porn Fetch. It will be available in v3.1 :)
