### ISSUE TITLE
Download flagged as trojan

### ISSUE THREAD

**Issue by haminhtrifree** [EchterAlsFake/Porn_Fetch#40]
Virustotal shows your .exe download file as trojan for +10 scanning software man.

**Comment by EchterAlsFake** [comment]
Update:

I have now implemented a mechanism into the build scripts, so that every new release of Porn Fetch will be built from source and the compiled release will be visible for everyone. This will additionally also show the SHA 512 hash of every file. 

With this everyone is able to 100% verify that I did NOT modify the files. This gives everyone who can read code a guarantee that the downloaded file is not modified by a third party.


Explanation:

The GitHub CI/CD actions are a seperate virtual machine which allows a repository owner to automate tasks such as creating releases, merging pull requests or in my case compiling source code to a binary file. The script which creates this process is publicly available in my repository source code under  ".github/workflows/" 

While this workflow is running I am not able in any way to interact with it. This means that I can't change code or modify files on the system. So it's technically not possible for me to modify anything. The hash at the end for every file is digitally unique to this file. This means, that if the hash of the compiled file by the GitHub CI/CD and the file which will be in my release matches, than it's 100% the same in any way.
