### ISSUE TITLE
Automation of Porn Fetch

### ISSUE THREAD

**Issue by LionelDavila** [EchterAlsFake/Porn_Fetch#64]
Hey,

just wanted to ask is there some way to automate porn fetch to automatically download my whole Pornhub history every 5 hours without needing to manually trigger it?

Thanks in advance :)

**Comment by EchterAlsFake** [comment]
Hi, sorry that it took so long.

It is possible through the PHUB API. If you can code you can have a look at it, but if not then I need to say that I won't implement such a feature because it's a very special use case and it would mean a lot of code for one person.

I hope you don't feel bad about it. Have a nice day!
